### PR TITLE
added russian translate "ZK Basics Cheatsheet"

### PR DESCRIPTION
**Pull request by v1docq47**
added 2 files with translation "ZK Basics Cheatsheet":
* ZKbasicsCS/translations/ru/ZKbasicsCheatsheet20220621.docx
* ZKbasicsCS/translations/ru/ZKbasicsCheatsheet20220621.pdf

### CODE REVIEW

**Comment by baro77** [comment]
thanks v1docq47... I just noticed a couple of things to fix:

- background color of "Completeness" (bottom left) is wrong: it should be two-color
-in my logo in the bottom right, clicking both the avatar or the balloon the PDF will open https://github.com/baro77 but the baloon should open https://github.com/baro77/ZKbasicsCS

thank you very much for your effort, and sorry for me being late in getting them

**Comment by v1docq47** [comment]
@baro77, tnx! made edits

**Comment by baro77** [comment]
Hi @v1docq47 
the problems in bottom-right links seem not fixed yet... could you try again? I have verified the problem is present in the .docx as well, so I my educated guess is that the macro zone pointing to https://github.com/baro77 is in the foreground with respect to the balloon zone pointing to https://github.com/baro77/ZKbasicsCS, so the latter is overloaded... maybe playing with layers or the order by which you include the two links could fix the stuff. Thanks!

**Comment by v1docq47** [comment]
@baro77, made edits, can check :)

**Comment by baro77** [comment]
Hi @v1docq47 !
first of all, thanks for your work. I guess this translation has been really hard given the topic, but happily it seems all the links are ok now.
I have noticed other problems as well, introduced by later editing I guess, but nothing serious:

- problem in drawing in "PZK" box: "<= n-1 times" missing, "S" cut
- gray box in lower part of "from IP to ZKP": right and left arrows are black instead of white
- in "ARK" box, "вычислительной целостностью" should be bold and underlined as in "ARG" box
- in "Fiat-Shamir" box, problems in drawing: "commitment" label missing, and multiple cut for labels "RO(statement, commitment)", "P", "V"

Thanks for your commitment.. it seems just these few steps are missing before the merge :-)

**Comment by v1docq47** [comment]
@baro77, and one more try :)

**Comment by baro77** [comment]
@v1docq47 seems ok, except that we have reverted again to bottom right balloon/avatar link problem... I have checked .docx  with Word, and .pdf with macOS's Preview and Acrobat Reader: "https://github.com/baro77/ZKbasicsCS" compares only in Preview when floating with the mouse over the balloon, but clicking you are always redirected to https://github.com/baro77 as when clicking on the avatar....

**Comment by v1docq47** [comment]
@baro77, i transferred the bottom part from the original document. think it all worked out :D

**Comment by baro77** [comment]
@v1docq47 thanks to your perseverance! Seems all ok, I just squashed to the last commit and merged it... citing it in the README and adding it to bybaro.it/tss soon

**Pull request merged**
